name: Generate Slide Previews

on:
  push:
    branches: [main]
    paths: 
      - 'slides/**'
      - 'scripts/build-index.js'
  workflow_dispatch:

jobs:
  generate-previews:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build slides
        run: npm run build:slides
        
      - name: Start local server
        run: |
          cd dist
          python3 -m http.server 3000 &
          sleep 5
        
      - name: Generate preview images
        run: npm run generate-previews
        
      - name: Check if previews changed
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain dist/previews/)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Commit preview images
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/previews/
          git commit -m "🖼️ Auto-update slide preview images [skip ci]"
          git push
